#sonar.projectKey=courseCatalog
#sonar.sources=.
#sonar.exclusions=**/*.html,**/*.css,**/*.js,**/*.yaml,**/*.xml
#sonar.javascript.enabled=false
#sonar.typescript.enabled=false
#sonar.css.enabled=false
